name: Tests

on: [push, pull_request]

jobs:
  python34:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.4

      - name: Install dependencies
        run: make init-34

      - name: Test
        run: make test

  modern-python:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: make init

    - name: Format
      run: make format

    - name: Lint
      run: make lint

    - name: Coverage
      run: make coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
