name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        # MicroPython is close to 3.4
        # TODO: Use MicroPython itself
        include:
          - coveralls: false
            python-version: "3.4"
            os: ubuntu-18.04
          - coveralls: true
            python-version: "3.10"
            os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: make

    - name: Lint
      if: matrix.coveralls == true
      run: make lint

    - name: Test
      if: matrix.coveralls == false
      run: make test

    - name: Coverage
      if: matrix.coveralls == true
      run: make coverage

    - name: Coveralls
      if: matrix.coveralls == true
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
